### PR TITLE
Add C# Hashing

### PR DESCRIPTION
**Pull request by mtalent**

### CODE REVIEW

**Comment by mtalent** [comment]
I've never done this before I think I did it right........

Thanks for the plugin I hope I can help others

**Comment by jpmens** [comment]
Are `*.pdb` files really something I want to have in a repository? Also, I don't want the `*.exe` in there. 

I can easily remove those though.

**Comment by mtalent** [comment]
I have never created a pull before, so I wasn't sure how to do it. (or what to include) I can easily make changes if you want just tell me what to do.  Thanks again for all your hard work.  I am now having a hell of a time with the ssl connection using m2mqtt client in C# but thats for another day.  :)


________________________________

**Comment by jpmens** [comment]
What I meant was: are pdb files something you as programmer provide or are they generated by a compiler (like .exe files are)

**Comment by mtalent** [comment]
They are generated by the compiler and are not necessary.  They provide debugging information (I looked it up just now), I will remove them and the exe's and provide another pull


________________________________

**Comment by mtalent** [comment]
The changes I made are above can you merge from there??

**Comment by jpmens** [comment]
Merged thanks.

**Pull request merged**
