### PR TITLE
Added mongo ACL checking

### PR DESCRIPTION
**Pull request by Spekko**
Hi 

I created an issue a few minutes ago but I see it should have been a pull request >.<. Sorry, still new to github.
Anyway, I have filled in the ACL check in be-mongo.c and it seems to be working on my side.
I will do the superuser check soon

### CODE REVIEW

**Comment by jpmens** [comment]
Sorry, I cannot take this as it is because:

1. You have changed the Makefile and I don't see why you've done that. Most things ought to be configurable from `config.mk`
2. Too many hardcoded parameters in `be-mongo.c` (e.g. dbName, colName, etc)
3. be_mongo_aclcheck(): you've changed `conf` to `handle` without valid reason. We use `conf` all over the place.
4. Finally, you've completely clobbered `config.mk.in`. Why did you do *that*?

**Comment by Spekko** [comment]
sorry, will clean up. 
My mosquitto installed to a different lib so I had to modify, will use defaults.

**Comment by Spekko** [comment]
I have committed a cleanup, I was probably just excited to commit to a first contribution sorry xD.

**Comment by jpmens** [comment]
This is indeed, much better, and I'll take it even though I cannot test.
Merged, thank you!

**Pull request merged**
