### PR TITLE
shell executable on top of provided PHP script

### PR DESCRIPTION
**Pull request by slavino**
PHP CLI hash gen

### CODE REVIEW

**Comment by jpmens** [comment]
What does this add other than a hash bang (#!) line?

**Comment by slavino** [comment]
for *nix users "chmod u+x *.sh" will make it executable from command line will end up in this CLI output

~/workspace/mosquitto-auth-plug/contrib $ ./genhash.sh TestPassword

PBKDF2$sha256$901$+ddKEUSIGgC6o74u$eHQnWIfCou5bpAShmYUXq08AjclAAfMY

**Comment by jpmens** [comment]
I understand that. What I meant was "what value" does it add? As far as I see you've simply copied the orignal and added a wrapper. If people can't do that by themselves they shouldn't be using this software IMO.

Furthermore, we already have a password-generating program called `np` in the distribution.

I appreciate your effort, but you'll have to convince me that this *adds value*. :-)

**Comment by slavino** [comment]
Right and valid point :D

**Comment by jpmens** [comment]
Don't let that discourage you: I'm happy to take contributions, and I know how much work it is to create one.

**Comment by slavino** [comment]
No problem. And makes sense. Wouldn't like to have mess in own repos either.

**Pull request closed without merging**
