### PR TITLE
Add hostname at JWT Backend

### PR DESCRIPTION
**Pull request by MrCrunsh**

### CODE REVIEW

**Comment by jpmens** [comment]
Thanks for your contribution.

Please see if you can consolidate most of that code: this is what I "see" (but it's completely untested, so please verify as I cannot compile / test here):

```
snprintf(url, sizeof(url), "%s://%s:%d/%s",
        strcmp(conf->with_tls, "true") == 0 ? "https" : "http",
        conf->hostname ? conf->hostname : conf->ip,
        conf->port,
        conf->uri);
```

That single `snprintf` does it all. Please note the `n` in `snprintf`.

**Comment by MrCrunsh** [comment]
It don't work:

```
be-jwt.c: In function 'http_post':
be-jwt.c:151:13: error: 'struct jwt_backend' has no member named 'uri'
         conf->uri);
             ^~
be-jwt.c:147:22: error: argument to 'sizeof' in 'snprintf' call is the same expression as the destination; did you mean to provide an explicit length? [-Werror=sizeof-pointer-memaccess]
  snprintf(url, sizeof(url), "%s://%s:%d/%s",
```

**Comment by MrCrunsh** [comment]
I change ` conf->uri` to `uri` but i get still exeptions (cast exeptions and pointer/tye exeptions).

**Comment by MrCrunsh** [comment]
This don't work, too

```
sprintf(url, "%s://%s:%d/%s",
        strcmp(conf->with_tls, "true") == 0 ? "https" : "http",
        conf->hostname ? conf->hostname : conf->ip,
        conf->port,
        uri);
```
This only use the IP and ignored a given Hostname.

I think my solution is not the best one but it still work ;-)

**Comment by jpmens** [comment]
Thank you for your contribution. I have consolidated the code as proposed.

**Pull request closed without merging**
