### PR TITLE
Create Authentication Cache

### PR DESCRIPTION
**Pull request by nishi13**
Hey i dont know if its gona be useful but i created a authentication cache, but i removed ClientId from the cache because in my case those where random,

### CODE REVIEW

**Comment by jpmens** [comment]
I like this but think the clientid should be in there because we can have ACLs with clientid in them. Can you add clientid (even if it's within `#ifdef`)?

**Comment by brandond** [comment]
@nishi13 I'd love to use this, but I too would like to make ClientID part of the cache entry. Any chance for an update?

**Comment by nishi13** [comment]
Hey its been a while since i did this, i dont i think i can.

**Comment by wiebeytec** [comment]
I'm confused. How does this differ with the cache that's already in the auth plugin?

**Comment by brandond** [comment]
@wiebeytec it's been a bit since I looked at it, but if I remember correctly, the existing code caches ACL lookups but not authentication requests. It's an authorization cache, not an authentication cache, so to speak.

**Comment by wiebeytec** [comment]
Ah, of course. Never mind then :).

**Comment by jpmens** [comment]
Closed via #253

**Pull request closed without merging**
